/* Business Question #11 - Top Customers by Revenue

-- Business Context
The Marketing Team wants to identify the highest-value customers
based on the total revenue they generated.

-- Business Question
Which customers generated the highest total revenue?
*/

-- QUERY

SELECT
    c.CustomerID,
    c.CustomerName,
    SUM(o.Quantity * o.UnitPrice * (1 - o.DiscountPct)) AS TotalRevenue
FROM Orders o
INNER JOIN Customers c
    ON o.CustomerID = c.CustomerID
GROUP BY
    c.CustomerID,
    c.CustomerName
ORDER BY
    TotalRevenue DESC;


/* Business Question #12 - Customer Performance by Location

-- Business Context
Management wants to compare customer revenue
across different locations.

-- Business Question
Which customer locations generate the highest revenue?
*/

-- QUERY

SELECT
    c.City,
    COUNT(DISTINCT c.CustomerID) AS TotalCustomers,
    SUM(o.Quantity * o.UnitPrice * (1 - o.DiscountPct)) AS TotalRevenue
FROM Orders o
INNER JOIN Customers c
    ON o.CustomerID = c.CustomerID
GROUP BY
    c.City
ORDER BY
    TotalRevenue DESC;


/* Business Question #13 - Repeat Purchase Customers

-- Business Context
The Marketing Team wants to identify loyal customers
who have made multiple purchases.

-- Business Question
Which customers have placed more than one order?
*/

-- QUERY

SELECT
    c.CustomerID,
    c.CustomerName,
    COUNT(DISTINCT o.OrderID) AS TotalOrders
FROM Orders o
INNER JOIN Customers c
    ON o.CustomerID = c.CustomerID
GROUP BY
    c.CustomerID,
    c.CustomerName
HAVING COUNT(DISTINCT o.OrderID) > 1
ORDER BY
    TotalOrders DESC;


/* Business Question #14 - Customer Lifetime Value (CLV)

-- Business Context
The Sales Team wants to measure the lifetime value
of each customer.

-- Business Question
What is the lifetime revenue generated by each customer?
*/

-- QUERY

SELECT
    c.CustomerID,
    c.CustomerName,
    SUM(o.Quantity * o.UnitPrice * (1 - o.DiscountPct)) AS CustomerLifetimeValue
FROM Orders o
INNER JOIN Customers c
    ON o.CustomerID = c.CustomerID
GROUP BY
    c.CustomerID,
    c.CustomerName
ORDER BY
    CustomerLifetimeValue DESC;


/* Business Question #15 - New vs Returning Customers

-- Business Context
Management wants to understand the balance between
new and returning customers.

-- Business Question
How many customers are new and how many are returning?
*/

-- QUERY

WITH CustomerOrders AS (
    SELECT
        CustomerID,
        COUNT(DISTINCT OrderID) AS TotalOrders
    FROM Orders
    GROUP BY CustomerID
)

SELECT
    CASE
        WHEN TotalOrders = 1 THEN 'New Customer'
        ELSE 'Returning Customer'
    END AS CustomerType,
    COUNT(*) AS TotalCustomers
FROM CustomerOrders
GROUP BY
    CASE
        WHEN TotalOrders = 1 THEN 'New Customer'
        ELSE 'Returning Customer'
    END;


/* Business Question #16 - Average Spending per Customer

-- Business Context
The Finance Team wants to understand
the average spending behavior of customers.

-- Business Question
What is the average amount spent by each customer?
*/

-- QUERY

SELECT
    c.CustomerID,
    c.CustomerName,
    AVG(o.Quantity * o.UnitPrice * (1 - o.DiscountPct)) AS AverageOrderValue
FROM Orders o
INNER JOIN Customers c
    ON o.CustomerID = c.CustomerID
GROUP BY
    c.CustomerID,
    c.CustomerName
ORDER BY
    AverageOrderValue DESC;


/* Business Question #17 - Most Active Customers

-- Business Context
The Sales Team wants to identify customers
who place orders most frequently.

-- Business Question
Which customers have placed the highest number of orders?
*/

-- QUERY

SELECT
    c.CustomerID,
    c.CustomerName,
    COUNT(DISTINCT o.OrderID) AS TotalOrders
FROM Orders o
INNER JOIN Customers c
    ON o.CustomerID = c.CustomerID
GROUP BY
    c.CustomerID,
    c.CustomerName
ORDER BY
    TotalOrders DESC;


/* Business Question #18 - Customer Purchase Frequency

-- Business Context
Management wants to understand how frequently
customers make purchases.

-- Business Question
How many days, on average, are there between purchases for each customer?
*/

-- QUERY

WITH PurchaseHistory AS (
    SELECT
        CustomerID,
        OrderDate,
        LAG(OrderDate) OVER (
            PARTITION BY CustomerID
            ORDER BY OrderDate
        ) AS PreviousOrderDate
    FROM Orders
)

SELECT
    CustomerID,
    AVG(DATEDIFF(DAY, PreviousOrderDate, OrderDate) * 1.0) AS AvgDaysBetweenPurchases
FROM PurchaseHistory
WHERE PreviousOrderDate IS NOT NULL
GROUP BY CustomerID
ORDER BY AvgDaysBetweenPurchases;


/* Business Question #19 - Inactive Customers

-- Business Context
The Marketing Team wants to identify customers
who have not made purchases recently.

-- Business Question
Which customers have not placed an order in the last 90 days?
*/

-- QUERY

SELECT
    c.CustomerID,
    c.CustomerName,
    MAX(o.OrderDate) AS LastPurchaseDate
FROM Orders o
INNER JOIN Customers c
    ON o.CustomerID = c.CustomerID
GROUP BY
    c.CustomerID,
    c.CustomerName
HAVING MAX(o.OrderDate) < DATEADD(DAY, -90, GETDATE())
ORDER BY
    LastPurchaseDate;


/* Business Question #20 - Customer Revenue Ranking

-- Business Context
Management wants to rank customers
based on their total revenue contribution.

-- Business Question
How does each customer rank by total revenue generated?
*/

-- QUERY

SELECT
    c.CustomerID,
    c.CustomerName,
    SUM(o.Quantity * o.UnitPrice * (1 - o.DiscountPct)) AS TotalRevenue,
    RANK() OVER (
        ORDER BY SUM(o.Quantity * o.UnitPrice * (1 - o.DiscountPct)) DESC
    ) AS RevenueRank
FROM Orders o
INNER JOIN Customers c
    ON o.CustomerID = c.CustomerID
GROUP BY
    c.CustomerID,
    c.CustomerName
ORDER BY
    RevenueRank;
