/* Business Question #31 - Top Sales Employees

-- Business Context
Management wants to identify
the highest-performing sales employees.

-- Business Question
Which employees generate the highest total revenue?
*/

-- QUERY

SELECT
    e.EmployeeID,
    e.EmployeeName,
    SUM(o.Quantity * o.UnitPrice * (1 - o.DiscountPct)) AS TotalRevenue
FROM Orders o
INNER JOIN Employees e
    ON o.EmployeeID = e.EmployeeID
GROUP BY
    e.EmployeeID,
    e.EmployeeName
ORDER BY
    TotalRevenue DESC;


/* Business Question #32 - Revenue per Employee

-- Business Context
Management wants to evaluate
each employee's revenue contribution.

-- Business Question
How much revenue has each employee generated?
*/

-- QUERY

SELECT
    e.EmployeeID,
    e.EmployeeName,
    SUM(o.Quantity * o.UnitPrice * (1 - o.DiscountPct)) AS TotalRevenue
FROM Employees e
LEFT JOIN Orders o
    ON e.EmployeeID = o.EmployeeID
GROUP BY
    e.EmployeeID,
    e.EmployeeName
ORDER BY
    TotalRevenue DESC;


/* Business Question #33 - Employee Sales Ranking

-- Business Context
Management wants to rank employees
based on their sales performance.

-- Business Question
What is the sales ranking of each employee?
*/

-- QUERY

SELECT
    e.EmployeeID,
    e.EmployeeName,
    SUM(o.Quantity * o.UnitPrice * (1 - o.DiscountPct)) AS TotalRevenue,
    RANK() OVER (
        ORDER BY
            SUM(o.Quantity * o.UnitPrice * (1 - o.DiscountPct)) DESC
    ) AS SalesRank
FROM Orders o
INNER JOIN Employees e
    ON o.EmployeeID = e.EmployeeID
GROUP BY
    e.EmployeeID,
    e.EmployeeName
ORDER BY
    SalesRank;


/* Business Question #34 - Average Revenue per Employee

-- Business Context
Management wants to measure
the average revenue generated by employees.

-- Business Question
What is the average revenue generated per employee?
*/

-- QUERY

SELECT
    AVG(EmployeeRevenue) AS AverageRevenue
FROM
(
    SELECT
        EmployeeID,
        SUM(Quantity * UnitPrice * (1 - DiscountPct)) AS EmployeeRevenue
    FROM Orders
    GROUP BY EmployeeID
) AS EmployeeSales;


/* Business Question #35 - Employees Without Sales

-- Business Context
Management wants to identify employees
who have not generated any sales.

-- Business Question
Which employees have no sales records?
*/

-- QUERY

SELECT
    e.EmployeeID,
    e.EmployeeName
FROM Employees e
LEFT JOIN Orders o
    ON e.EmployeeID = o.EmployeeID
WHERE
    o.OrderID IS NULL
ORDER BY
    e.EmployeeID;


/* Business Question #36 - Highest Order Volume by Employee

-- Business Context
Management wants to compare
employee productivity based on order volume.

-- Business Question
Which employees handle the highest number of orders?
*/

-- QUERY

SELECT
    e.EmployeeID,
    e.EmployeeName,
    COUNT(DISTINCT o.OrderID) AS TotalOrders
FROM Orders o
INNER JOIN Employees e
    ON o.EmployeeID = e.EmployeeID
GROUP BY
    e.EmployeeID,
    e.EmployeeName
ORDER BY
    TotalOrders DESC;


/* Business Question #37 - Average Order Value by Employee

-- Business Context
Management wants to compare
the average value of orders handled by employees.

-- Business Question
What is the average order revenue for each employee?
*/

-- QUERY

SELECT
    e.EmployeeID,
    e.EmployeeName,
    AVG(o.Quantity * o.UnitPrice * (1 - o.DiscountPct)) AS AverageOrderValue
FROM Orders o
INNER JOIN Employees e
    ON o.EmployeeID = e.EmployeeID
GROUP BY
    e.EmployeeID,
    e.EmployeeName
ORDER BY
    AverageOrderValue DESC;


/* Business Question #38 - Department Revenue Contribution

-- Business Context
Management wants to measure
revenue contribution across departments.

-- Business Question
How much revenue does each department contribute?
*/

-- QUERY

SELECT
    d.DepartmentName,
    SUM(o.Quantity * o.UnitPrice * (1 - o.DiscountPct)) AS TotalRevenue
FROM Orders o
INNER JOIN Employees e
    ON o.EmployeeID = e.EmployeeID
INNER JOIN Departments d
    ON e.DepartmentID = d.DepartmentID
GROUP BY
    d.DepartmentName
ORDER BY
    TotalRevenue DESC;


/* Business Question #39 - Best Employee in Each Department

-- Business Context
Management wants to identify
the highest-performing employee in each department.

-- Business Question
Who is the top revenue-generating employee in every department?
*/

-- QUERY

WITH EmployeeRevenue AS
(
    SELECT
        d.DepartmentName,
        e.EmployeeID,
        e.EmployeeName,
        SUM(o.Quantity * o.UnitPrice * (1 - o.DiscountPct)) AS TotalRevenue,
        ROW_NUMBER() OVER
        (
            PARTITION BY d.DepartmentName
            ORDER BY
                SUM(o.Quantity * o.UnitPrice * (1 - o.DiscountPct)) DESC
        ) AS RowNum
    FROM Orders o
    INNER JOIN Employees e
        ON o.EmployeeID = e.EmployeeID
    INNER JOIN Departments d
        ON e.DepartmentID = d.DepartmentID
    GROUP BY
        d.DepartmentName,
        e.EmployeeID,
        e.EmployeeName
)

SELECT
    DepartmentName,
    EmployeeID,
    EmployeeName,
    TotalRevenue
FROM EmployeeRevenue
WHERE RowNum = 1
ORDER BY
    DepartmentName;


/* Business Question #40 - Employee Monthly Performance Trend

-- Business Context
Management wants to monitor
employee sales performance over time.

-- Business Question
How does employee revenue change each month?
*/

-- QUERY

SELECT
    e.EmployeeID,
    e.EmployeeName,
    YEAR(o.OrderDate) AS SalesYear,
    MONTH(o.OrderDate) AS SalesMonth,
    SUM(o.Quantity * o.UnitPrice * (1 - o.DiscountPct)) AS MonthlyRevenue
FROM Orders o
INNER JOIN Employees e
    ON o.EmployeeID = e.EmployeeID
GROUP BY
    e.EmployeeID,
    e.EmployeeName,
    YEAR(o.OrderDate),
    MONTH(o.OrderDate)
ORDER BY
    e.EmployeeName,
    SalesYear,
    SalesMonth;
