/* Business Question #61 - Average Quantity per Order

-- Business Context
Management wants to understand
the average number of products purchased per order.

-- Business Question
What is the average quantity sold per order?
*/

-- QUERY

SELECT
    AVG(OrderQuantity) AS AverageQuantityPerOrder
FROM
(
    SELECT
        OrderID,
        SUM(Quantity) AS OrderQuantity
    FROM Orders
    GROUP BY OrderID
) AS OrderSummary;


/* Business Question #62 - Largest Orders

-- Business Context
Management wants to identify
the largest customer orders.

-- Business Question
Which orders generate the highest revenue?
*/

-- QUERY

SELECT
    o.OrderID,
    c.CustomerName,
    SUM(o.Quantity * o.UnitPrice * (1 - o.DiscountPct)) AS TotalRevenue
FROM Orders o
INNER JOIN Customers c
    ON o.CustomerID = c.CustomerID
GROUP BY
    o.OrderID,
    c.CustomerName
ORDER BY
    TotalRevenue DESC;


/* Business Question #63 - Orders by City

-- Business Context
Management wants to analyze
order distribution across cities.

-- Business Question
How many orders are placed in each city?
*/

-- QUERY

SELECT
    c.City,
    COUNT(DISTINCT o.OrderID) AS TotalOrders
FROM Orders o
INNER JOIN Customers c
    ON o.CustomerID = c.CustomerID
GROUP BY
    c.City
ORDER BY
    TotalOrders DESC;


/* Business Question #64 - Sales by Department

-- Business Context
Management wants to evaluate
sales performance by department.

-- Business Question
How much revenue is generated by each department?
*/

-- QUERY

SELECT
    d.DepartmentName,
    SUM(o.Quantity * o.UnitPrice * (1 - o.DiscountPct)) AS TotalRevenue
FROM Orders o
INNER JOIN Employees e
    ON o.EmployeeID = e.EmployeeID
INNER JOIN Departments d
    ON e.DepartmentID = d.DepartmentID
GROUP BY
    d.DepartmentName
ORDER BY
    TotalRevenue DESC;


/* Business Question #65 - Employee Workload Analysis

-- Business Context
Management wants to compare
employee workloads.

-- Business Question
How many orders has each employee handled?
*/

-- QUERY

SELECT
    e.EmployeeID,
    e.EmployeeName,
    COUNT(DISTINCT o.OrderID) AS TotalOrdersHandled
FROM Employees e
LEFT JOIN Orders o
    ON e.EmployeeID = o.EmployeeID
GROUP BY
    e.EmployeeID,
    e.EmployeeName
ORDER BY
    TotalOrdersHandled DESC;


/* Business Question #66 - Daily Order Volume

-- Business Context
Management wants to monitor
daily operational activity.

-- Business Question
How many orders are processed each day?
*/

-- QUERY

SELECT
    OrderDate,
    COUNT(DISTINCT OrderID) AS TotalOrders
FROM Orders
GROUP BY
    OrderDate
ORDER BY
    OrderDate;


/* Business Question #67 - Average Processing Volume per Employee

-- Business Context
Management wants to evaluate
employee processing capacity.

-- Business Question
What is the average number of orders handled by each employee?
*/

-- QUERY

SELECT
    AVG(EmployeeOrders) AS AverageOrdersPerEmployee
FROM
(
    SELECT
        EmployeeID,
        COUNT(DISTINCT OrderID) AS EmployeeOrders
    FROM Orders
    GROUP BY EmployeeID
) AS EmployeeSummary;


/* Business Question #68 - Cities with Highest Sales

-- Business Context
Management wants to identify
the strongest sales markets.

-- Business Question
Which cities generate the highest sales revenue?
*/

-- QUERY

SELECT
    c.City,
    SUM(o.Quantity * o.UnitPrice * (1 - o.DiscountPct)) AS TotalRevenue
FROM Orders o
INNER JOIN Customers c
    ON o.CustomerID = c.CustomerID
GROUP BY
    c.City
ORDER BY
    TotalRevenue DESC;


/* Business Question #69 - Product Mix per Order

-- Business Context
Management wants to analyze
product variety within customer orders.

-- Business Question
How many different products are included in each order?
*/

-- QUERY

SELECT
    OrderID,
    COUNT(DISTINCT ProductID) AS NumberOfProducts
FROM Orders
GROUP BY
    OrderID
ORDER BY
    NumberOfProducts DESC;


/* Business Question #70 - Peak Operational Days

-- Business Context
Management wants to identify
the busiest operational days.

-- Business Question
Which days have the highest order volume?
*/

-- QUERY

SELECT
    DATENAME(WEEKDAY, OrderDate) AS DayName,
    COUNT(DISTINCT OrderID) AS TotalOrders
FROM Orders
GROUP BY
    DATENAME(WEEKDAY, OrderDate)
ORDER BY
    TotalOrders DESC;
