/* Business Question #81 - Pareto Analysis (80/20)

-- Business Context
Management wants to identify
whether a small percentage of customers
contribute the majority of revenue.

-- Business Question
Which customers contribute approximately 80% of total revenue?
*/

-- QUERY

WITH CustomerRevenue AS
(
    SELECT
        c.CustomerID,
        c.CustomerName,
        SUM(o.Quantity * o.UnitPrice * (1 - o.DiscountPct)) AS TotalRevenue
    FROM Orders o
    INNER JOIN Customers c
        ON o.CustomerID = c.CustomerID
    GROUP BY
        c.CustomerID,
        c.CustomerName
),
RevenueRank AS
(
    SELECT
        *,
        SUM(TotalRevenue) OVER
        (
            ORDER BY TotalRevenue DESC
        ) AS RunningRevenue,
        SUM(TotalRevenue) OVER () AS OverallRevenue
    FROM CustomerRevenue
)

SELECT
    CustomerID,
    CustomerName,
    TotalRevenue,
    RunningRevenue,
    OverallRevenue,
    ROUND(RunningRevenue * 100.0 / OverallRevenue,2) AS CumulativePct
FROM RevenueRank
ORDER BY
    TotalRevenue DESC;
/* Business Question #82 - Revenue Contribution by Customer Segment

-- Business Context
Management wants to compare
revenue across customer segments.

-- Business Question
How much revenue is generated by each customer segment?
*/

-- QUERY

SELECT
    c.CustomerSegment,
    SUM(o.Quantity * o.UnitPrice * (1 - o.DiscountPct)) AS TotalRevenue
FROM Orders o
INNER JOIN Customers c
    ON o.CustomerID = c.CustomerID
GROUP BY
    c.CustomerSegment
ORDER BY
    TotalRevenue DESC;
/* Business Question #83 - Top 20% Customers

-- Business Context
Management wants to identify
the highest-value customers.

-- Business Question
Who are the top 20% customers based on revenue?
*/

-- QUERY

WITH CustomerRevenue AS
(
    SELECT
        c.CustomerID,
        c.CustomerName,
        SUM(o.Quantity * o.UnitPrice * (1 - o.DiscountPct)) AS TotalRevenue
    FROM Orders o
    INNER JOIN Customers c
        ON o.CustomerID = c.CustomerID
    GROUP BY
        c.CustomerID,
        c.CustomerName
)

SELECT TOP (20) PERCENT
    CustomerID,
    CustomerName,
    TotalRevenue
FROM CustomerRevenue
ORDER BY
    TotalRevenue DESC;
/* Business Question #84 - Revenue Share by Product Category

-- Business Context
Management wants to understand
the revenue contribution of each category.

-- Business Question
How much revenue does each product category contribute?
*/

-- QUERY

SELECT
    ca.CategoryName,
    SUM(o.Quantity * o.UnitPrice * (1 - o.DiscountPct)) AS TotalRevenue
FROM Orders o
INNER JOIN Products p
    ON o.ProductID = p.ProductID
INNER JOIN Categories ca
    ON p.CategoryID = ca.CategoryID
GROUP BY
    ca.CategoryName
ORDER BY
    TotalRevenue DESC;
/* Business Question #85 - Executive KPI Summary

-- Business Context
Executives need a single report
containing key business metrics.

-- Business Question
What are the company's key sales KPIs?
*/

-- QUERY

SELECT
    COUNT(DISTINCT OrderID) AS TotalOrders,
    COUNT(DISTINCT CustomerID) AS TotalCustomers,
    COUNT(DISTINCT ProductID) AS TotalProducts,
    SUM(Quantity) AS TotalQuantitySold,
    SUM(Quantity * UnitPrice * (1 - DiscountPct)) AS TotalRevenue,
    SUM((UnitPrice - UnitCost) * Quantity * (1 - DiscountPct)) AS TotalProfit
FROM Orders;
/* Business Question #86 - Customer Revenue Distribution

-- Business Context
Management wants to understand
customer revenue distribution.

-- Business Question
How is revenue distributed among customers?
*/

-- QUERY

SELECT
    c.CustomerID,
    c.CustomerName,
    SUM(o.Quantity * o.UnitPrice * (1 - o.DiscountPct)) AS TotalRevenue
FROM Orders o
INNER JOIN Customers c
    ON o.CustomerID = c.CustomerID
GROUP BY
    c.CustomerID,
    c.CustomerName
ORDER BY
    TotalRevenue DESC;
/* Business Question #87 - Product Revenue Distribution

-- Business Context
Management wants to understand
product revenue distribution.

-- Business Question
How is revenue distributed across products?
*/

-- QUERY

SELECT
    p.ProductID,
    p.ProductName,
    SUM(o.Quantity * o.UnitPrice * (1 - o.DiscountPct)) AS TotalRevenue
FROM Orders o
INNER JOIN Products p
    ON o.ProductID = p.ProductID
GROUP BY
    p.ProductID,
    p.ProductName
ORDER BY
    TotalRevenue DESC;
/* Business Question #88 - Revenue by Region

-- Business Context
Management wants to compare
sales performance across regions.

-- Business Question
How much revenue is generated by each city?
*/

-- QUERY

SELECT
    c.City,
    SUM(o.Quantity * o.UnitPrice * (1 - o.DiscountPct)) AS TotalRevenue
FROM Orders o
INNER JOIN Customers c
    ON o.CustomerID = c.CustomerID
GROUP BY
    c.City
ORDER BY
    TotalRevenue DESC;
/* Business Question #89 - Top Performing Business Areas

-- Business Context
Management wants to identify
the highest-performing business departments.

-- Business Question
Which departments generate the highest revenue?
*/

-- QUERY

SELECT
    d.DepartmentName,
    SUM(o.Quantity * o.UnitPrice * (1 - o.DiscountPct)) AS TotalRevenue
FROM Orders o
INNER JOIN Employees e
    ON o.EmployeeID = e.EmployeeID
INNER JOIN Departments d
    ON e.DepartmentID = d.DepartmentID
GROUP BY
    d.DepartmentName
ORDER BY
    TotalRevenue DESC;
/* Business Question #90 - Executive Sales Dashboard Dataset

-- Business Context
Executives require a consolidated dataset
to support strategic decision-making.

-- Business Question
What dataset can be prepared
for an executive sales dashboard?
*/

-- QUERY

SELECT
    o.OrderID,
    o.OrderDate,
    c.CustomerID,
    c.CustomerName,
    c.CustomerSegment,
    c.City,
    p.ProductID,
    p.ProductName,
    ca.CategoryName,
    e.EmployeeName,
    d.DepartmentName,
    o.Quantity,
    o.UnitPrice,
    o.UnitCost,
    o.DiscountPct,
    (o.Quantity * o.UnitPrice * (1 - o.DiscountPct)) AS Revenue,
    ((o.UnitPrice - o.UnitCost) * o.Quantity * (1 - o.DiscountPct)) AS Profit
FROM Orders o
INNER JOIN Customers c
    ON o.CustomerID = c.CustomerID
INNER JOIN Products p
    ON o.ProductID = p.ProductID
INNER JOIN Categories ca
    ON p.CategoryID = ca.CategoryID
INNER JOIN Employees e
    ON o.EmployeeID = e.EmployeeID
INNER JOIN Departments d
    ON e.DepartmentID = d.DepartmentID;
